name: Meowy
version: '${project.version}'
main: com.earthpol.meowy.Meowy
api-version: '1.20'
folia-supported: true
commands:
  meow:
    description: Meow like a cat person.
    usage: /meow <args>
  meowy:
    description: Tells you about Meowy.
    usage: /meowy
  mew:
    description: Determines if you gain rizz or no rizz.
    usage: /mew